"""DeepAudit prompt templates."""

from .orchestrator_prompt import ORCHESTRATOR_SYSTEM_PROMPT
from .recon_prompt import RECON_SYSTEM_PROMPT
from .analysis_prompt import ANALYSIS_SYSTEM_PROMPT
from .verification_prompt import VERIFICATION_SYSTEM_PROMPT
from .shared_sections import (
    CORE_SECURITY_PRINCIPLES,
    FILE_VALIDATION_RULES_V2_1,
    VULNERABILITY_PRIORITIES,
    TOOL_USAGE_GUIDE,
    MULTI_AGENT_RULES,
    TOOL_PLACEHOLDER,
    VERIFICATION_VERDICT_CRITERIA,
)

__all__ = [
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "RECON_SYSTEM_PROMPT",
    "ANALYSIS_SYSTEM_PROMPT",
    "VERIFICATION_SYSTEM_PROMPT",
    "CORE_SECURITY_PRINCIPLES",
    "FILE_VALIDATION_RULES_V2_1",
    "VULNERABILITY_PRIORITIES",
    "TOOL_USAGE_GUIDE",
    "MULTI_AGENT_RULES",
    "TOOL_PLACEHOLDER",
    "VERIFICATION_VERDICT_CRITERIA",
]
